worknenjoy/gitpay

- frontend/src/components/welcome/welcome.js
> Menu click should navigate to right section
> Main page navigation (Welcome)
- `git checkout xavierleonardo/bugfix/navigarion-menu-update`
> Fix mobile navigion offset

- modules/mail/deadline.js
> The second action about deadline notifications should be about the issue url, as we don't have a route to handle options like extend deadline yet
> On review
> #000
> Backend on email notifications
> [HOTFIX] Adding task url as secondary action on deadline notifications

- frontend/src/components/profile/country-picker.js
> When running tests with ```npm run test```, it fails with this message:
```
/home/vagrant/gitpay/frontend/src/components/profile/country-picker.js
101:62  error  Expected indentation of 14 space characters but found 12  react/jsx-indent
✖ 1 problem (1 error, 0 warnings)
1 error, 0 warnings potentially fixable with the `--fix` option.
```
- [ frontend/src/components/profile/country-picker.js ] fixed the spacing on line 101
> #000
> cli test
- run ```npm run test```
- observe that the test is now successful
> Fix spacing

- modules/app/controllers/webhook.js
There was no language management with i18n to send the various emails.
The emails were therefore always sent in English.
Added i18n configuration.
And in each case I have inserted the setLocale with the language that the user has set.
> #173 
> Only in webhook.js
> FIX: solved i18n language problem inside webhook.js

- locales/br.json
- locales/en.json
- locales/result/br.json
- locales/result/en.json
- modules/app/controllers/webhook.js
- modules/mail/issueClosed.js
- server.js
- test/webhook.test.js
> This allows to sync the issue status on Github with our website.
- /modules/app/controllers/webhooks.js
- /test/webhook.test.js
> #484 
> I've added update query so database gets updated.
>All the pages where issue status is displayed
- I have added the test in `/test/webhook.test.js`
- Similar to the test you can create your own and test if the thing works.
*Some other steps you can follow(requires postman)*
- Start the backend server.
- (Optional)Start pgAdmin to see change in database.
- Send post requests through postman with the data as json.
> Feat/sync issues status with GitHub webhooks

- .env.example
- frontend/package.json
This PR removes quotes from the environment variable that specifies the frontend app host.
For some reason NodeJS doesn't remove them on Linux (it does on Mac OS).
I have no experience en NodeJS, so I didn't dig further, maybe a follow-up request could fix this differently, but at least this will unblock docker environment.
It also adds the `invert-color` dependency to the frontend packages as stated in the [issue comment](https://github.com/worknenjoy/gitpay/issues/460#issuecomment-591065211)
-  .`env.example`
- `frontend/package.json`
> #460 
> Login
Clone this branch and follow these steps:
- `cp .env.example .env`
- `docker-compose up`
- Run `docker container exec gitpay_backend_1 npm run migrate`
- Run `docker container exec gitpay_backend_1 npm run seed` 
- Browse …
> Fix FRONTEND_HOST env variable

- frontend/src/components/task/task.js
> After "learning purposes" and "Agreed to terms" checkboxes are selected, the submit button now becomes available as expected.
- Task's "Make Offer" form.
> #507 
> Task page
- Go to an issue.
- Click on "Make an Offer"
- Check the "learning purposes" and "agree to tems" checkboxes.
> ![image](https://user-images.githubusercontent.com/12785530/77158446-b6484c80-6a79-11ea-85aa-d6424460c5ed.png)
> ![image](https://user-images.githubusercontent.com/12785530/77158485-c95b1c80-6a79-11ea-9c82-a494cd2402e6.png)
> Fixed issue #507.

- frontend/src/components/task/task-table.js
when a user clicks on the provider link(Github or BitBucket) should go to a new tab.
A new tab is opened when a user clicks on a provider link.
#529 
A  user can navigate to a different tab to see an issue.
> Main page
- Create Task
- Click on provider link(Github or BitBucket)
>![ice_screenshot_20200404-191830](https://user-images.githubusercontent.com/11736897/78458438-393bea80-76a9-11ea-9d3b-227d1b75a06c.png)
> ![ice_screenshot_20200404-192052](https://user-images.githubusercontent.com/11736897/78458460-730cf100-76a9-11ea-9bc2-addffd98e34e.png)
> Fixed issue(#529)

- modules/tasks/taskUpdate.js
#Description
fixing of Duplicated user on the user interested tab so that if a user is to submit to be interested to work on a particular issue more than once, this will not produce duplicate record.
#Changes 
implementation of a conditional check if a user (by userId and taskId) already exist in an array of assigns for a particular task.
taskUpdate.js
#517  
> Closes #517
> Main page
run app
-Create a user - user1
-Import an issue with the user1
-Create another user - user2
-Apply to solve that issue created by user1 from user2
Apply again
Only a single entry will be recorded.
> fixing of Duplicated user on the interested user section of task.

- modules/app/controllers/auth.js
- test/task.test.js
- GitHub will replace and discontinue OAuth endpoints containing access_token in the path parameter. We are introducing new endpoints that allow you to securely manage tokens for OAuth Apps by using access_token as an input parameter. The OAuth Application API will be removed on July 1, 2020
- Gitpay used its client_id and client_secret  as part of a set of query parameters to access an endpoint through the GitHub API
- Use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated and will be removed July 1st, 2020
- Use Basic Authentication instead as using OAuth credentials in query parameters.
Closes #452 
[[GITPAY] Deprecation notice for authentication via URL query parameters](https://gitpay.me/#/task/315)
- Backend Controller Auth
- Create / log …
> [GitHub API] Deprecation notice for authentication via URL query parameters

- frontend/src/components/task/task.js
We need to display who is the original author (from Github or Bitbucket) and who created on Gitpay
gitpay/frontend/src/components/task/task.js
> Closes #000
Task page
- Create Task
- Other steps
> #541 add another avatar on task page

- modules/app/controllers/webhook.js
- package-lock.json
> add support for all currencies when a payout intransit email is sent using the payout.created webhook
- in ``/modules/app/controllers/webhooks.js``
> Closes #548
> In email template in files ``/locales/en.json``
- no test in local env
> add currency support for payout created webhook

- frontend/src/components/task/task.js
now only one tab will open either add bounty or deadline.
now only one tab will remain open either the add bounty or the deadline tab
changes were made in task.js to resolve the issue
> Closes #504 
> task page
- Create user
- import a issue
- Click on bounty tab and then deadline tab (now only one will remain open)
> resolved issue #504

- models/order.js
- modules/bot/comment.js
> When an issue from Github imported to Gitpay and a bounty is added, add a comment on this issue:
A bounty of 10USD was added to this issue. See task on Gitpay: {{url}}
Unfortunately the bot would be not able to add Label to the issue since only the owner or member can do it.
- Added Hook on Offer to trigger when paid and commenting on issue.
- Need to add GITHUB_BOT_ACCESS_TOKEN= to .env
- Generate Token for [https://github.com/gitpaybot](https://github.com/gitpaybot)
[Create Access Token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)
> closes #562 
> Front-End Task
> Back-End: Offer Model
- Create Task
- Add a bounty and pay
- A comment will be added into github issue
> Issue #562

- locales/en.json
- modules/mail/assign.js
This PR removes Email information for assigned user from following emails contents and both locale
Having subjects
1.Someone is interested in a task that you created on Gitpay
2. You have assigned {{name}} to do a task
> modules/mail/assign.js
> locales/en.json
>Closes #530
> AssignMail.owner.interested
> AssignMail.owner.assigned
-create an user
-Import an issue
-Create another user
-Apply to solve an issue in I'm interested (An email should be sent with subject 'Someone is interested in a task that you created on Gitpay')
-Log with the first user
-Assign user
-Accept from Second user (An email should be sent with subject 'You have assigned {{name}} to do a task')
> fix(assign):remmoval of email information of assigned user

- frontend/src/components/task/task-payment-form.js
- frontend/src/components/task/task.js
> To avoid orphans orders, and no possibility to check if the user owns that order in order to edit, we should require login first
> Closes #497 
> Payments
> Adding login box if the user try to add a bounty without signin

- frontend/src/components/task/task-status-filter.js
> Changed task-status-filter.js styles object
- task-status-filter.js
> Closes #653 
> Tasks page
- Go to https://gitpay.me/#/tasks/all
- Change between other options like open, in progress etc and observe the styling
> <img width="539" alt="Screenshot 2020-08-29 at 16 17 34" src="https://user-images.githubusercontent.com/41532077/91635115-5041f700-ea13-11ea-9df6-84ead392da7f.png">
> Fixed button style on click (clip style)

- docker-compose.test.yml
- docker-compose.yml
> Fixed db service in docker-compose.yml doesn't loading required variables to Postgres image, cause of it the docker does not work correctly.
- Added `env_file` property in db service as the others services in docker-compose.yml
- Added `POSTGRES_PASSWORD` variable in docker-compose.test.yml
> Development in docker
- Just start the services on docker-compose.yml
> Fix Postgres does not loading correctly environment variables

- frontend/src/components/task/task-tabs.js
> The task history tab was showing the wrong user on create. Was showing the logged in user.
- Change the line to show the task user creator
> Closes #518 
> Main page
- Create Task
- Other steps
> Fix wrong user on task user

- modules/users/userAccountCreate.js
Removing `legacy_payments` to capabilities when creating an account
> removing legacy_payments to capabilities

- models/plan.js
- modules/orders/orderBuilds.js
- modules/tasks/taskUpdate.js
> Charges with an amount equal to zero are causing an error with the stripe request.
- Changing function name calFinalPrice to calcFinalPrice on Plan's model
- Changing the conditional related to avoid a charge request to stripe with amount equals to zero
> Closes #894
> Credit Card payment
- Create Task
- Create a payment for the task created using credit card
> N/A
> N/A
> Issue #894

- frontend/src/components/task/task-assignment.js
The translation are missing in the task assignment text area
the website donth swith to portuguese in localhost, and generate this error in the console:
i submitting this PR with the hotfix but will be better test in all languages before merging, please give me the instructions to test it or let's try in a staging environment
> Fix Task Assignment translation missing

- .circleci/config.yml
- frontend/src/components/task/task-table.js
> supposed to Closes #1013 (not yet)
To allow user to sort the columns in a table
To allow user to sort the columns in a table
Using **TableSortLabel** component from **MUI**, Got  to know about it after seeing the PR's related to this issue.
**None**
None
None
Fork the repo and create your branch from master. -  done
If you've added code that should be tested, add tests. - not yet
If you've changed APIs, update the documentation. - NA
Ensure the test suite passes. - tests on previous codebase are failing
Make sure your code lints. - linting on previous codebase are failing
Issue that pull request! - going to do it
Check if the build is green before we start to review - waiting
Thank you.
> Fix for Issue #1013

- frontend/src/components/task/task-table.js
- pmd.xml
> Closes #1013
- Added sorting functionality to make it easier for users to organize and find tasks based on different criteria.
- Introduced dynamic sorting for each column (Task, Status, Project, Value, Labels, Created At).
- Implemented ascending and descending sorting based on user preferences with reset sort on third click
- Refactored the code for better readability and maintainability.
- Introduced metadata for table headers to enhance code organization.
The purpose of this pull request is to enhance the task table component by introducing sorting functionality for better organization and dynamic sorting based on user preferences. Additionally, the code structure has been refactored to improve readability and maintainability.
The solution involves implementing sorting capabilities …
> Allow user sort

- frontend/src/components/design-library/templates/payment-drawer/payment-drawer.tsx
- frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx
- frontend/src/components/profile/components/payments/add-funds-invoice-tab.tsx
- frontend/src/components/task/payment/methods/wallet/payment-method-wallet-tab.tsx
- models/wallet.js
- test/order.test.js
- test/walletOrder.test.js
This pull request includes changes to the payment and wallet handling logic in the frontend and backend, as well as corresponding updates to the tests. The most important changes involve modifying how prices and fees are handled and updating the wallet balance calculations.
* [`frontend/src/components/design-library/templates/payment-drawer/payment-drawer.tsx`](diffhunk://#diff-ac8540cbed094e28d54202f1fcaa1ad45a50b54e2a439e7dcb8f82f10b5fce1eL101-R101): Updated the `PricePlan` component to conditionally pass the `plan` prop based on the `tabValue` to handle different payment scenarios.
* [`frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx`](diffhunk://#diff-a2383530ea7160c15d3d05d7be3bb01f1dfd996d8420db4556fc74558acd42a0R42-R50): Added a new `plan` object to the …
> Making Wallet order add a fee when pay

- frontend/src/components/design-library/templates/payment-drawer/payment-drawer.tsx
- frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx
- frontend/src/components/task/payment/methods/wallet/payment-method-wallet-tab.tsx
- models/wallet.js
- test/order.test.js
- test/walletOrder.test.js
This pull request includes multiple changes to the frontend components and backend models related to payment processing and wallet functionality. The most important changes focus on standardizing the fee calculations and updating the wallet balance logic.
* [`frontend/src/components/design-library/templates/payment-drawer/payment-drawer.tsx`](diffhunk://#diff-ac8540cbed094e28d54202f1fcaa1ad45a50b54e2a439e7dcb8f82f10b5fce1eL101-R101): Simplified the `PricePlan` component by always passing the `plan` prop.
* [`frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx`](diffhunk://#diff-a2383530ea7160c15d3d05d7be3bb01f1dfd996d8420db4556fc74558acd42a0L43-R48): Updated the fee and plan details for the wallet payment method. …
> changing fee to be applied only when fund bounty for wallet payment@

- frontend/src/components/design-library/templates/task-deadline-drawer/task-deadline-drawer.tsx
- frontend/src/components/task/task-deadline-form.js
- frontend/src/components/task/task.js
- frontend/src/translations/br.json
- frontend/src/translations/en.json
- frontend/src/translations/generated/br.json
- frontend/src/translations/generated/en.json
Closes #1132
Created a new TaskDeadlineDrawer component to handle task deadline functionality in a consistent drawer pattern, matching the design of OfferDrawer and PaymentDrawer components. Fixed issues with date display and alignment.
- Move the deadline form into a drawer component for better UI consistency
- Fix date display issues where existing dates weren't showing up
- Improve the UI/UX of the deadline form with better button states and alignment
- Add clear date functionality
1. Created new TaskDeadlineDrawer component
2. Updated TaskDeadlineForm with:
- Fixed date initialisation from props
- Added dateChanged state to control button text
- Improved date field and label alignment
- Added clear date functionality
3. Updated Task component to use new drawer
> Add TaskDeadlineDrawer

- frontend/src/components/profile/TextMaskCustom.tsx
- frontend/src/components/profile/account-details.tsx
> Closes #1173
This PR refactors the phone number masking logic by moving it into a separate reusable component (TextMaskCustom). This improves code maintainability and resolves issues where, when accept the terms in the account registration form is toggled, the phone field clears up.
Explain the purpose of this pull request and the problem it aims to solve.
1).Extracted the phone number masking logic into a dedicated component (TextMaskCustom.tsx).
2).Fixed the issue by properly managing focus and event handling in the TextMaskCustom component.
3).Updated the AccountDetails.tsx file to import and use the new TextMaskCustom component instead of defining the masking inline.
Tested input behavior to ensure smooth typing without phone field clearing up.
Include any relevant screenshots or …
> fix:fix bug where phone field clears on accepting terms

- test/webhook.connect.test.js
- test/webhook.platform.test.js
This pull request refactors the webhook tests by renaming the test file and updating the webhook endpoint paths to distinguish between standard and Stripe Connect webhooks. The changes improve clarity and organization for testing different webhook types.
* Renamed `test/webhook.test.js` to `test/webhook.connect.test.js` to better reflect its focus on Stripe Connect webhooks.
* Updated all instances of `.post('/webhooks')` to `.post('/webhooks/stripe-connect')` in the renamed test file to specify the Stripe Connect webhook endpoint. This change ensures that the tests target the correct endpoint. [[1]](diffhunk://#diff-3112bb48444e86b04e869661909510437efe1a4cb6589d6acffced3d9862abe5L43-R43) [[2]](diffhunk://#diff-3112bb48444e86b04e869661909510437efe1a4cb6589d6acffced3d9862abe5L76-R76) …
> test: separate webhook platform and connect tests

- frontend/src/components/areas/public/features/task/language-filter.stories.tsx
- frontend/src/components/areas/public/features/task/task-explorer.js
- frontend/src/components/areas/public/features/task/task-filter-labels.stories.tsx
- frontend/src/components/areas/public/features/task/task-filters.stories.tsx
- frontend/src/containers/task-explorer.js
Closes #1202 
Added the same filters available on the logged user explore page (`/profile/explore`) to the public explore page (`/tasks/open`), providing consistent filtering functionality across both interfaces.
This PR implements the requested feature to display filters on the public explore page that were previously only available to logged-in users. The implementation ensures both pages now have identical filtering capabilities.
1. **Enhanced TaskExplorer Container** (`frontend/src/containers/task-explorer.js`)
- Added `filterTasks` action import and dispatch
- Added tasks data access via `mapStateToProps`
- Connected filtered tasks selector
2. **Updated TaskExplorer Component** (`frontend/src/components/areas/public/features/task/task-explorer.js`)
- Imported `TaskFiltersContainer` …
> feat: add filters to public explore page

- frontend/src/components/areas/private/components/profile-sidebar.tsx
- frontend/src/components/design-library/molecules/menus/side-menu/side-menu-items.tsx
- frontend/src/components/design-library/molecules/menus/side-menu/side-menu.styled.div.js
- frontend/src/components/design-library/molecules/menus/side-menu/side-menu.tsx
This pull request introduces a significant refactor and enhancement of the side menu component in the frontend. The changes focus on modularizing the code, improving the responsiveness of the side menu, and enhancing the user experience with mobile-friendly features. The most important changes are grouped into modularization, styling improvements, and mobile responsiveness.
* Extracted menu item rendering logic into a new `SideMenuItems` component for better code organization and reusability (`side-menu-items.tsx`).
* Moved styles from `TopbarStyles` to a new `side-menu.styled.div` file, enabling the use of `styled-components` for cleaner and more maintainable styling.
* Added new `useStyles` definitions to improve layout and alignment, including responsive adjustments for smaller screens …
> supporting mobile menu for private pages

- frontend/src/actions/taskSolutionActions.js
- frontend/src/components/areas/public/features/task/components/send-solution-drawer.tsx
- frontend/src/containers/send-solution-drawer.js
- modules/app/controllers/taskSolution.js
- test/taskSolution.test.js
This pull request simplifies the handling of `userId` by removing it from the payloads and API requests in various parts of the application. Instead, the `userId` is now consistently derived from the authenticated user context (`req.user.id`) on the backend. The changes span across the frontend, backend, and test files, ensuring uniformity and reducing redundant data passing.
* Removed `userId` from the parameters of `getTaskSolution`, `fetchPullRequestData`, and `updateTaskSolution` functions in `frontend/src/actions/taskSolutionActions.js`. Updated API calls to exclude `userId` from query parameters. [[1]](diffhunk://#diff-06ac2231e87bd3922ba7745d36d725b9e5afd3ed55788addd2070ce837da96c3L45-R49) [[2]](diffhunk://#diff-06ac2231e87bd3922ba7745d36d725b9e5afd3ed55788addd2070ce837da96c3L80-R85 …
> assigning current user session for all task solution endpoints

- modules/util/handle-amount/handle-amount.js
- test/handle-amount.test.js
This pull request updates the rounding logic in the `handleAmount` utility function and adds a new test case to ensure correct behavior when applying percentages that cause rounding. The main changes are:
**Rounding Logic Update:**
* The `centavos` value in `handleAmount` is now always rounded to the nearest whole number, regardless of the currency's decimal places. This ensures consistency and accuracy when converting amounts.
**Test Coverage Improvements:**
* Added a new test to verify that applying an 8 percent deduction to an amount results in correct rounding for both `centavos` and `decimal` values.
> handling amount convertion in centavos

- frontend/src/components/areas/private/features/claims/claims.tsx
- frontend/src/components/areas/private/features/payouts/payouts-table.tsx
- frontend/src/components/design-library/atoms/status/payout-status/payout-status.stories.tsx
- frontend/src/components/design-library/atoms/status/payout-status/payout-status.styles.ts
- frontend/src/components/design-library/atoms/status/payout-status/payout-status.tsx
- frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.stories.tsx
- frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.styles.ts
- frontend/src/components/design-library/atoms/status/transfer-status/transfer-status.tsx
- frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/payouts/payout-status-field/payout-status-field.stories.tsx
- frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/payouts/payout-status-field/payout-status-field.tsx
- frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/transfer/transfer-status-field/transfer-status-field.stories.tsx
- frontend/src/components/design-library/molecules/tables/section-table/section-table-custom-fields/transfer/transfer-status-field/transfer-status-field.tsx
This pull request introduces new, specialized status components for payout and transfer records, and integrates them into the claims and payouts tables in the frontend. The changes improve the clarity and consistency of status displays by replacing generic status fields with custom-designed components and styles, and add Storybook stories for easier UI testing and documentation.
**Status Component Enhancements**
* Added new `PayoutStatus` and `TransferStatus` atom components, each with custom icons, labels, color-coded styles, and status messages for various payout/transfer states. These components use a shared `BaseStatus` for consistent rendering. (`frontend/src/components/design-library/atoms/status/payout-status/payout-status.tsx` …
> new payment status and transfer components
