worknenjoy/gitpay

- modules/load/controllers/webhook.js
- test/data/charge.js
- test/data/payout.js
- test/webhook.test.js
More webhooks when a charge is updated and paid out completed to the destionation account
> adding more webhooks

- config/passport.js
Handling when github didn't return the email from auth login or create account
> raise error if is not possible to fetch github user email

- frontend/src/actions/taskActions.js
- frontend/src/components/task/task-list.js
> creating basic filters on task list

- frontend/src/actions/taskActions.js
- frontend/src/components/task/task-list.js
- frontend/src/containers/task-list.js
> getting task filter always get tasks data

- config/passport.js
- frontend/src/components/profile/account.js
- frontend/src/components/task/task.js
- loading/task.js
- loading/user.js
- migration/migrations/20180626131108-add-title-to-task.js
- migration/migrations/20180626132835-add-repourl-to-user.js
- modules/tasks/taskBuilds.js
- modules/tasks/taskFetch.js
- test/task.test.js
Besides that, now the tests is faster cause it not request the github api if the provider is not github
> linking the task title from api and github profile url

- frontend/src/actions/userActions.js
- frontend/src/components/profile/account.js
> fixing account issues on activation

- frontend/src/components/welcome/welcome.js
> Adjust of Text

- modules/tasks/taskBuilds.js
- modules/tasks/taskFetch.js
> Task-44 - Using github client id and secret when fetching tasks

- docker-compose.test.yml
- docker-compose.yml
- modules/load/controllers/webhook.js
- modules/mail/mail.js
- test/data/balance.js
- test/webhook.test.js
> Sending notification when new balance is hit

- frontend/src/components/profile/profile.js
> Fixed click bug at Preference menu

- frontend/src/components/task/task.js
- modules/tasks/taskSync.js
> Overlapping images on description of a task

- config/secrets.js
- modules/mail/assign.js
- modules/mail/constants.js
- modules/mail/handleError.js
- modules/mail/handleResponse.js
- modules/mail/mail.js
- modules/mail/payment.js
- modules/mail/request.js
- modules/mail/transfer.js
> Task 40 - Checking sendgrid's api key and refactoring mailing methods

- modules/mail/transfer.js
- modules/tasks/taskPayment.js
- modules/tasks/taskUpdate.js
> Notification about new transfer for a non activated account

- frontend/src/actions/taskActions.js
- frontend/src/components/task/task-invite.js
- frontend/src/components/task/task.js
- frontend/src/containers/task.js
- frontend/src/reducers/taskReducer.js
- modules/load/controllers/task.js
- modules/load/routes/tasks.js
- modules/tasks/index.js
- modules/tasks/taskInvite.js
- test/task.test.js
> Invite user to checkout a new task

- frontend/src/components/task/task.js
Foi preciso somente corrigir o timezone para a data aparecer no dia correto.
> Added timezone.

- frontend/src/components/topbar/TopbarStyles.js
- frontend/src/components/topbar/topbar.js
To allow more space for clear options on home page, I moved the logo to the left and added the documentation link
> New nav bar with logo on the left

- frontend/src/translations/br.json
Updating a text for translation
> Updating text in br

- frontend/webpack.config.js
> fix file-loader mistakenly handle other files

- frontend/src/actions/helpers/index.js
- frontend/src/actions/orderActions.js
- frontend/src/actions/preferencesActions.js
- frontend/src/actions/taskActions.js
- frontend/src/actions/userActions.js
- modules/load/controllers/auth.js
- modules/load/controllers/task.js
- modules/load/routes/auth.js
- modules/load/routes/secure.js
- modules/tasks/removeAssignedUser.js
- modules/tasks/taskDeleteById.js
- test/helpers/index.js
- test/task.test.js
- test/user.test.js
Secure sensitive routes, inject user id on the backend, update tests and frontend actions accordingly.
> Don't use client supplied user id (#245)

- README.md
Added arch commands to install docker.
> Added steps to install Docker on Arch

- README.md
> my-first-contributing-in-open-source-project

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
- frontend/webpack.config.prod.js
> updating webpack version and dependencies

- frontend/src/components/task/task-assigned.js
- frontend/src/components/task/task.js
- frontend/src/reducers/taskReducer.js
- modules/tasks/taskFetch.js
a card that display on the task page who is assigned and the current status
> Assigned card

- frontend/src/components/task/task-list.js
cherry-pick from @Claudiogoncalves #313
> fixing merge of claudio changes about the task filter router

- frontend/src/components/welcome/welcome.js
> Navigation menu should be auto updated as we scroll sections of the mais page
> On review
> #311 
> Main page
> Fix main navigation to follow the sections as we scroll the page

- frontend/src/components/welcome/welcome.js
I will have to revert this solution cause is not working properly and actually broke the UI scroll on home page, waiting for @xavierleonardo to send a new solution
Reverts worknenjoy/gitpay#330
> Revert "Fix main navigation to follow the sections as we scroll the page"

- frontend/src/components/welcome/welcome.js
> Navigation menu should be auto updated as we scroll sections of the mais page
> On review
> Main page navigation
- `git checkout bugfix/main-navigarion-scroll-sections`
> Fix main navigation to focus right link menu

- frontend/src/components/welcome/welcome.js
> Navigation menu should be auto updated as we scroll sections of the main page and on click
> Main page navigation
- `git checkout bugfix/main-navigarion-scroll-sections`
> Fix main menu focus browser compatibility

- migration/migrations/20190328210733-add-status-to-assigns.js
- models/assign.js
> On review
> #000
> Main page
> adding status to assign

- frontend/src/components/welcome/pricing.js
> reviewing pricing options

- cron.js
- frontend/src/components/payment/payment-options.js
- frontend/src/components/profile/account.js
- frontend/src/components/profile/organizations.js
- frontend/src/components/profile/profile.js
- test/cron.test.js
> Fixing bug when account is created and improvements for user account
- [x ] User profile and account
> Fixing bug when account is created and improvements for user account

- .eslintignore
- frontend/package-lock.json
- frontend/package.json
- frontend/sitemap-builder.js
- frontend/sitemap.xml
- frontend/src/main/routes-sitemap.js
> related to issue #143 , which creates a simple sitemap for google
> On review
> Feature/issue #143

- config/passport.js
- frontend/src/actions/organizationsActions.js
- frontend/src/components/profile/organizations.js
- frontend/src/components/profile/profile.js
- frontend/src/containers/profile.js
- frontend/src/reducers/organizationsReducer.js
- frontend/src/reducers/reducers.js
- frontend/tests/actions/actions.test.js
- frontend/tests/reducers/reducers.test.js
- migration/migrations/20190523201059-create-organization.js
- models/organization.js
- models/user.js
- modules/app/controllers/organization.js
- modules/app/index.js
- modules/app/routes/organization.js
- modules/organizations/index.js
- modules/organizations/organizationBuilds.js
- modules/users/userOrganizations.js
- test/organization.test.js
- test/user.test.js
> Organization GitHub import
- [ x ] Profile
> On review
> Profile
> Feature/Organization GitHub import

- modules/tasks/taskPayment.js
- modules/tasks/taskUpdate.js
> Starting with the 8% fees as base fee of the platform
- [ x ] Charges and transfers
> Adding application fee of 8 percent to charge and transfer

- README.md
Added Caio Reis as a first timer
- [ line 116 ]
> On review
> #247
> Main page
> Added Caio Reis as a first timer

- frontend/package-lock.json
- frontend/src/components/task/task.js
After the #270 merged, a bug was introduced when assign user
> Fixing the bug when try to assign / unassign user
> On review
> #270 
> Main page
> passing assign and unassign to task tabs to fix the bug when assign user

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main/app.js
> On review
> #000
> Main page
> adding logrocket

- frontend/src/components/topbar/TopbarStyles.js
- frontend/src/components/topbar/topbar.js
Create basic css animate in menu hamburger
> On review
> #379 
> Main page
> animated menu hamburger

- frontend/package-lock.json
- modules/tasks/taskBuilds.js
- modules/tasks/taskFetch.js
- package-lock.json
> Migrate Bitbucket to v2
> Tested and approved
> See issue and create issue from Bitbucket
> updating api to v2 in order to show issues from bitbucket again

- frontend/src/components/session/login-button.js
- frontend/src/components/task/task-header.js
- frontend/src/components/task/task-payment.js
- frontend/src/components/task/task-tabs.js
- frontend/src/components/task/task.js
- frontend/src/components/topbar/topbar.js
- modules/app/controllers/auth.js
- modules/app/routes/auth.js
- modules/tasks/taskBuilds.js
- modules/tasks/taskFetch.js
- test/data/github.auth.token.js
- test/task.test.js
- test/user.test.js
> Allow to add private projects from github with oauth to ask the permissions to access user repos
> Approved
> No issue related
> Create task
- Add a new task from github
- Check private
- Ask user permissions
- Task created
> Feature/private GitHub projects

- README.md
> #000
> Main page
- Create Task
- Other steps
> Updated the Readme as a first contribution to OS

- README.md
> Adds database seeding steps to README.md
> #410
> Adds database seeding steps to README.md

- modules/app/controllers/webhook.js
- modules/tasks/removeAssignedUser.js
- modules/tasks/taskSync.js
- modules/tasks/taskUpdate.js
- test/task.test.js
Set status automatically when someone is assigned, unassigned and if some issue imported has triggered a transfer.
> adding automatic status when someone is assigned, unassigned and paid

- cron.js
- modules/app/controllers/order.js
- modules/orders/orderCancel.js
- test/cron.test.js
- test/email.test.js
> A daily cron to check if a payment could be checked for paypal
> Notify paypal authorizations

- README.md
> #000
> Main page
- Create Task
- Other steps
> Update first timers

- cron.js
> Enabling latest tasks cron job

- frontend/src/components/task/messages/task-messages.js
- frontend/src/components/task/task-tabs.js
- frontend/src/translations/en.json
- locales/en.json
- modules/app/controllers/webhook.js
- modules/mail/task.js
- modules/mail/template.js
- package-lock.json
- test/data/refund.js
- test/webhook.test.js
> #000
> Main page
- Create Task
- Other steps
> implementing refund webhook

- frontend/src/components/profile/account.js
- frontend/src/components/profile/messages.js
- frontend/src/consts.js
- modules/users/userAccountCreate.js
The first part of the stripe update, in this case, to activate accounts to receive payments
- [ x ] Account activation
Create a new account to receive transfer
> Update stripe api as required for account connect

- README.md
> #000
> Main page
- Create Task
- Other steps
> Added my name as a first timer to the README.md

- README.md
> Update first timer list in README.md
- Added my name and profile link
> #247 
> Main page
> Read readme.md
> First timer PR

- frontend/package-lock.json
- frontend/src/components/task/messages/task-messages.js
- frontend/src/components/task/task-table.js
- frontend/src/components/task/task.js
- frontend/src/translations/en.json
No bounty added label
If value is 0 in tasks list, it displays 'No bounty added'
> #536 
> Main page
View on tasks page
> fix no bounty label

- modules/app/controllers/task.js
- modules/app/routes/secure.js
- modules/mail/assign.js
- modules/mail/request.js
- modules/tasks/taskMessage.js
- package-lock.json
> When an email is sent using our message system, it should send as the current user logged not the author.
- Changes apply to the message system where interested users can message each other now with the proper sender email(not the author's email as the sender) and receiver.
> #510
> Interested users of the Task where you can send emails to the interested users.
- Create / login user1
- Create Task with user1
- Create / login user2
- Click "I'm interested" on the first task created by user1
- Create / login user3
- Click "I'm interested" on the first task created by user1
- Login user1
- Assign the task to user2
- Login user2
- Message user3
You will need the Sendgrid keys to test the …
> Wrong email sender when send message to interested users

- frontend/src/actions/taskActions.js
- frontend/src/components/task/task.js
- frontend/src/containers/task.js
- locales/br.json
- locales/en.json
- modules/tasks/taskFunding.js
Add info about who is inviting
> Closes #000
> Main page
- Create Task
- Other steps
> Name invite sponsor

- frontend/src/components/loader/loader.js
- frontend/src/main/app.js
create loader component , implement loader logic in app component
- frontend/src/main.app , frontend/src/components/loader
> Closes #593 
> Main page
- Create / loader component
- Create Task
- Other steps
> Add loader

- frontend/src/components/session/login-form.js
> Improvement of password validation
- frontend > src > components > session > login-form.js
> closes #551 
> login page
> Improve password validation

- frontend/src/components/task/task.js
> Merge issue with loader component
- task.js
> Closes #502 
> Main page
- Create Task
- Other steps
> fix: issue with loader

- README.md
> Closes #000
> Main page
- Create Task
- Other steps
> Appended Full name + Github link to First Timers

- frontend/build/messages/src/components/profile/preferences.json
- frontend/src/actions/preferencesActions.js
- frontend/src/components/profile/preferences.js
- frontend/src/reducers/preferencesReducer.js
- frontend/tests/reducers/reducers.test.js
- migration/migrations/20190424115813-add-open-for-jobs-to-users.js
- models/user.js
- modules/users/userPreferences.js
> Open for Jobs checkbox for users on the preferences page.
- Checkbox added
> Closes #557 
> Preferences Page
- Create user
- Go to preferences
> #557 Open for Jobs checkbox for users

- frontend/src/actions/taskActions.js
- frontend/src/components/task/messages/task-messages.js
- frontend/src/components/task/task-status-filter.js
- frontend/src/containers/task-list.js
- frontend/src/main/routes.js
- frontend/src/reducers/taskReducer.js
- frontend/src/selectors/tasks.js
- frontend/src/translations/br.json
- frontend/src/translations/en.json
- frontend/src/translations/result/br.json
- frontend/src/translations/result/en.json
> Development of new labels to filter tasks in task list
- Task List Filter
- Task List Table
> Closes #465 
> Task list explorer
- Go to explore tasks
- Select a '$' or 'Contribution' filter label;
- Verify if the tasks filtered in task list are correct based on filter label selected;
> ![image](https://user-images.githubusercontent.com/21283066/80292609-df6d9400-872d-11ea-9114-02624c403445.png)
> ![image](https://user-images.githubusercontent.com/21283066/80292546-83a30b00-872d-11ea-9922-20a6976406e8.png)
> ![image](https://user-images.githubusercontent.com/21283066/80292562-91f12700-872d-11ea-8517-4fdcf5c1b09e.png)
> ![image](https://user-images.githubusercontent.com/21283066/8029258 …
> Issue #465

- README.md
> Closes #000
> Main page
- Create Task
- Other steps
> feat: #247 update readme

- modules/app/controllers/task.js
- modules/tasks/taskBuilds.js
- test/task.test.js
> check for 
Solve partially #625 to avoid tasks being created without the issue on Github.
> Adding verification if issue exist on Github

- frontend/src/components/profile/preferences.js
- changes apply to the preferences page
> Closes #553
> preferences tab in the profile section
- Create user
- go to preferences
> added React Native as preference

- locales/en.json
- scripts.js
- test/scripts.test.js
> A manual script to delete invalid tasks and notify the user
> Adding an email confirmation when the task is deleted on Gitpay

- README.md
> name added in readme

- README.md
contributor to readme profile
Added contributor 
ReadMe.md
> -update contributor readme

- frontend/src/components/profile/profile.js
> A better way to highlight the user profile
- modified `/frontend/src/components/profile/profile.js`
- TODO: Retrieve the number of tasks and bounties collected.
> #540 
> User Profile Card
Go to the /profile page
> ![image](https://user-images.githubusercontent.com/42090492/86116792-a2d26600-baeb-11ea-905c-12f416905c24.png)
> ![image](https://user-images.githubusercontent.com/42090492/86116761-951ce080-baeb-11ea-858a-3974f2e350ca.png)
> New profile card

- .vscode/launch.json
- modules/authenticationHelpers.js
- modules/users/index.js
- modules/users/userBounties.js
- modules/users/userExists.js
- modules/users/userTasks.js
- package-lock.json
> Completed tasks and collected bounties are now displayed on the user's profile.
- I created a new file ```./modules/users/usersTasks.js``` where I created a Promise method to find users tasks and bounties. I added this method to ```./modules/users/index``` and required it inside of ```./modules/authenticationHelpers.js``` to easily add the data to the user object
> Closes #684
> User Profile
- Create / log user A
- Create Task
- Create new user B
- Show interest in the task as user B
- Log in as user A
- Assign user B to task
- log in as user B 
- Accept task
- Log in as user A 
- Mark task as completed and pay user
- Log in as user B to view your profile
> Before changes implemented …
> Retrieve finished tasks and bounties

- frontend/package-lock.json
- frontend/src/components/payment/paypal-payment-dialog.js
- frontend/src/components/task/task-payment-form.js
- modules/orders/orderBuilds.js
- modules/orders/orderUpdate.js
Fixing plan choice not being passed on Paypal and null `TaskId`
When we implemented the plans feature, the Paypal payments stopped to work, and this PR fix by passing the right value to the PayPal API and fixing the null `TaskId` reference.
This was reported at https://github.com/electron-userland/electron-builder/issues/512#issuecomment-668691013
And once this PR is merged, we will have the Paypal payments working on the platform again.
- Paypal payments
> Fixing Paypal payment error when creating an order

- modules/mail/request.js
> Logging the content of all emails sent to make easier debug and avoid the need to send SendGrid API keys
> Mail logging

- modules/app/controllers/info.js
- test/info.test.js
> Removing the condition of tasks paid when displaying community amount info
> removing condition of paid for amount paid in the whole platform

- frontend/src/components/welcome/welcome.js
- frontend/src/translations/generated/en.json
> Simplifying the main tagline for the home page
> Changing main tagline

- frontend/src/components/team/team.js
> Insert member team

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/task/task.js
The text of the buttons in the bounty area was wrapping.  Now the text is on one line.
The change was to /frontend/src/components/task/task.js on line #257.
Closes #655 
https://prnt.sc/v5phtn
https://prnt.sc/v5pc24
> Fixed issue #655 'Adjust button text'

- frontend/src/components/task/task.js
- frontend/src/components/topbar/topbar.js
- migration/migrations/20210122093719-add-prviate-to-task.js
- models/task.js
- modules/app/controllers/auth.js
- modules/tasks/taskSearch.js
Adding issue private field to mark issue from private Github projects.
> Mark an issue as private and not list in public views

- frontend/src/components/task/task-header.js
- frontend/src/components/task/task-payments.js
- frontend/src/components/task/task.js
- frontend/src/main/app.css
- frontend/src/translations/generated/en.json
> Listing original author link and issue link and basic payments on an issue
> Issue redesign improvements

- frontend/src/components/task/task-header.js
- frontend/src/components/task/task-payments.js
> improvements to display payments
- Issue page
> Improvements on display payments on issue page

- frontend/src/components/task/task-header.js
- frontend/src/components/task/task-payments.js
- frontend/src/components/task/task.js
> display on the issue page just the paid orders
- Issue page
> More improvements on issue page

- frontend/src/components/profile/preferences.js
- modules/users/userUpdate.js
Fixing blank page in Preferences skills
- Preferences
> Preferences save fix

- frontend/src/components/task/assignment/AssignActions.js
- frontend/src/components/task/task-assigned.js
- frontend/src/components/task/task.js
> Fixing a bug that displays the send message to the assigned user and fixing send message action
- Issue page
> fixing assign message card display and action

- frontend/src/components/profile/profile.js
- frontend/src/components/topbar/topbar.js
- frontend/src/containers/topbar.js
> Improving profile navigation
> Profile navigation

- frontend/src/components/task/task-deadline-form.js
- frontend/src/components/task/task-level-split-button.js
- frontend/src/components/task/task.js
- frontend/src/translations/generated/br.json
- frontend/src/translations/generated/en.json
Status and deadline in the new redesign
> Status and deadline

- frontend/src/components/task/task-explorer.js
- frontend/src/components/topbar/topbar.js
> Revert "Issue #802"

- frontend/src/components/task/assignment/AssignActions.js
- frontend/src/components/task/task-assigned.js
- frontend/src/components/task/task.js
- modules/mail/assign.js
- modules/orders/orderBuilds.js
Create an option to create a new invoice from the offer
> Invoice offer

- modules/orders/orderUpdate.js
> Will trigger a comment in GitHub issue about the order created (PayPal provider) for the task.
- Order creation using PayPal
> Closes #803
> Make a payment for the task (PayPal)
- Import an issue
- Make a payment using Paypal
- The Github Bot should comment on that issue
> Screenshot from the state before (for now, not applies)
> Screenshot from the state after your Pull Request (for now, not applies)
> Issue #803

- modules/users/userAccountCreate.js
> Conditioning legacy payments for accounts different from GB

- modules/app/controllers/webhook.js
- modules/users/userAccountCreate.js
- test/webhook.test.js
> The order should be succeeded instead of paid from an invoice.
> Fixing status order update from paid to succeeded

- frontend/package-lock.json
- package-lock.json
> 
- Running docker on linux.
> Closes #000
> Main page
- docker-compose -f docker-compose-linux.yml up
> Running docker on linux

- modules/bot/issueAddedComment.js
- modules/tasks/taskBuilds.js
> Add a comment on Github using our bot when an issue is imported to Gitpay from Github.
- Task creation
> Closes #841 
> Main page
- Import an issue
> Issue #841

- frontend/src/components/organization/organization-card.js
- frontend/src/components/profile/profile.js
- frontend/src/components/topbar/topbar.js
- frontend/src/main/routes.js
Adding links to the public page
> adding links to the profile page and changing route

- frontend/src/components/task/task-list-user.js
> Closes #000
> Main page
- Create Task
- Other steps
> removing issues list as option for now

- modules/users/userAccountCreate.js
> Updating account with the new terms as recipient to support cross border payments
- Account onboarding
> updating terms and capatibilities to support new payments

- frontend/src/components/task/task-assignment.js
- migration/migrations/20220412120201-change-offer-comment-char-limit.js
- models/offer.js
- Change TextField to Textarea
- Create migrate to update comment char limit to 1000 on Offers table
Task Assignment
> Closes #888
> Update comment character limit on Task Assignment (#888)

- frontend/src/components/task/assignment/AssignActions.js
- frontend/src/components/task/task.js
- frontend/src/main/routes.js
- migration/migrations/20220404015828-add-active-to-user.js
- models/user.js
- modules/app/controllers/webhook.js
- test/data/stripe.invoice.paid.js
- test/webhook.test.js
> Feature to support orders created and paid from funding accounts to be recognized and processed correctly by Gitpay.
> Plus: Fixing an issue with the route when trying to accept the assignment to work on the task causing route not found.
- webhooks
- user model
- assign actions modal
> Closes #886 
> Assign actions modal
> User model
> Webhook
Steps needed to reproduce the scenario from this change to validate if the pull request solves this issue
- Create Task
- Accept an interested user to work on the created task
- Create an order when assigning the user to the task
- Validate the webhook received from stripe
> ![image](https://user-images.githubusercontent.com/21283066/162656788-6bf40929-502e-4b53-be36-5ca1e52db3c2.png)
> …
> Issue#886 - Update issue imported from Gitpay after receive an invoice paid webhook

- README.md
Updated readme file and added Linux instructions.
1. Slack channel link updated.
2. Added important notes regarding the need to use Node v12 and use npm install on backend and frontend folders (I think it can be useful for newbies like me).
3. Added Linux - Ubuntu instructions to install Postgres.
> read me updated with slack link and linux instructions

- frontend/package-lock.json
- frontend/package.json
> Revert "Bump flat and extract-react-intl-messages in /frontend"

- .circleci/config.yml
- .travis.yml
- README.md
- config/passport.js
- docker-compose-linux.yml
- docker-compose.test.yml
- docker-compose.yml
- frontend/src/components/task/task-payments.js
- frontend/src/components/topbar/topbar.js
- models/index.js
- modules/users/userExists.js
hey :wave: I have noticed some mismatches on the node config, also I did some required linter fixes to push this PR
---
Implementation details:
- update README
- update docker config
- update travis config
- update circleci config
- fix eslint errors
> Fix node version

- frontend/src/components/bottom/SlackCard.tsx
- frontend/src/components/profile/profile-options.js
- frontend/src/components/profile/profile.js
- frontend/src/components/profile/user-roles.js
- frontend/src/components/styles/palette.js
- frontend/src/components/topbar/TopbarStyles.js
- frontend/src/components/welcome/home.js
- frontend/src/containers/profile.js
- modules/tasks/requestAssignedUser.js
- modules/tasks/taskFetch.js
Logged navigation and some bugs fixed
> Logged navigation redesign

- frontend/src/components/session/login-button.js
- frontend/src/components/session/login-form.js
- frontend/src/components/session/login-page.js
- frontend/src/components/styles/palette.js
Login page redesigned with the new UX and ready for include "remember me" and "forgot password"
> Login page redesign

- frontend/src/components/profile/profile-options.js
- frontend/src/components/profile/profile.js
- frontend/src/components/styles/palette.js
- frontend/src/components/topbar/import-issue-dialog.tsx
- frontend/src/components/topbar/topbar.js
- frontend/src/containers/profile.js
> Closes #000
> Main page
- Create Task
- Other steps
> spliting topbar to extract the add issue dialog component

- frontend/src/components/payment/payment-options.js
- frontend/src/components/profile/account-details.tsx
- frontend/src/components/profile/account.js
- frontend/src/components/profile/components/account-tabs.tsx
- modules/users/userAccountCreate.js
- modules/users/userAccountUpdate.js
Remodeling the bank account activation, making more simple and facilitating the process to open an account
> feat: simplifying bank account activation and supporting Iban

- modules/transfers/transferBuilds.js
- test/helpers/index.js
- test/transfer.test.js
Some transfer improvements for multiple payments
> getting multiple providers transfer and fixing some transfer issues

- frontend/src/components/session/login-page.js
> fixing home page link

- frontend/src/actions/taskSolutionActions.js
- models/taskSolution.js
- modules/tasks/taskSolutionCreate.js
- modules/tasks/taskSolutionFetchData.js
- modules/tasks/taskSolutionUpdate.js
Fixing an issue when a `TaskSolution` is already created and needs to be updated
> fixing issues with task solution update to initiate a transfer

- frontend/src/components/profile/components/account-tabs.tsx
- frontend/src/components/profile/user-roles.js
> Closes #1086
I've refactored the code to improve code organization, performance, and maintainability. Here are the key changes:
1. In the component function, the initial value of the `value` state is set using the `getCurrentTab` function with the current URL path.
2. The `handleChange` function is memoized using the `useCallback` hook, and it updates the URL path based on the new tab value.
3. The `useEffect` hook uses the `history.listen` method to update the `value` state whenever the URL path changes. The `getCurrentTab` function is used to get the new tab value based on the updated URL path.
4. The `useEffect` hook also returns an `unlisten` function, which is used to clean up the listener when the component unmounts.
The rest of the component remains the same, rendering the tabs …
> Fix for User Account role update unneccessary rerender #1086

- frontend/src/actions/taskActions.js
- frontend/src/components/profile/user-tasks.js
- frontend/src/components/task/task-filters.tsx
- frontend/src/components/task/task-list.tsx
- frontend/src/containers/task-filter.js
- frontend/src/reducers/taskReducer.js
> Closes #00
Provide a brief description of the changes made in this pull request.
Explain the purpose of this pull request and the problem it aims to solve.
Provide a detailed explanation of the solution implemented and any relevant information. Include any code changes or new features.
Include any relevant screenshots or images to showcase the changes made.
Link any related issues that this pull request addresses.
Include any additional notes or information that may be relevant to this pull request.
Please ensure that your pull request follows the guidelines outlined in the project's [CONTRIBUTING.md](https://github.com/<username>/<repository>/blob/master/CONTRIBUTING.md) file.
Thank you for your contribution!
> task counter functionality added

- frontend/src/actions/taskActions.js
- frontend/src/common/navigation/breadcrumb.jsx
- frontend/src/components/profile/user-tasks.js
- frontend/src/components/task/task-header.js
- frontend/src/components/task/task-list.tsx
- frontend/src/components/topbar/import-issue-dialog.tsx
- frontend/src/selectors/tasks.js
- migration/migrations/20240819141150-add-not-listed-to-task.js
- models/task.js
- modules/tasks/taskFetch.js
- modules/tasks/taskSearch.js
Not listed option when importing issue and my issues tabs in projects and organization
> Not listed issues

- frontend/src/components/design-library/organisms/invoice-payment/invoice-payment.tsx
- frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx
- frontend/src/components/profile/components/payments/add-funds-invoice-tab.tsx
- frontend/src/components/profile/wallets.tsx
- frontend/src/components/profile/wallets/invoice-due-date.tsx
- frontend/src/components/profile/wallets/invoice-id.tsx
- frontend/src/components/task/messages/task-messages.js
- frontend/src/components/task/payment/methods/wallet/payment-method-wallet-tab.tsx
- frontend/src/components/task/task-payment-form.js
- models/wallet.js
- test/order.test.js
This pull request includes several changes to the invoicing and payment components, focusing on adding support for displaying invoice details and calculating prices with fees. The most important changes include updating the invoice payment message, adding new state variables and calculations for price after fees, and enhancing the wallet component to display invoice ID and due date.
* [`frontend/src/components/design-library/organisms/invoice-payment/invoice-payment.tsx`](diffhunk://#diff-3cf8da8abbddf8d74782a83afd0b8d8558ceda23c83e7c8c1d5b303f42020b90L76-R76): Updated the invoice payment message to "Generate a {amount} invoice" instead of "Pay {amount} with Invoice".
* [`frontend/src/components/profile/components/payments/add-funds-form-drawer.tsx`](diffhunk://#diff-a2383530ea7160c15d3d05 …
> Better handling of fees on wallet and more information about invoice

- frontend/src/components/design-library/atoms/price-input/price-input.tsx
- frontend/src/components/design-library/molecules/drawer/drawer.stories.tsx
- frontend/src/components/design-library/molecules/drawer/drawer.tsx
- frontend/src/components/design-library/molecules/introduction/introduction.stories.tsx
- frontend/src/components/design-library/molecules/introduction/introduction.tsx
- frontend/src/components/design-library/molecules/plan-card/plan-card.tsx
- frontend/src/components/design-library/organisms/price-plan/price-plan.tsx
- frontend/src/components/design-library/templates/payment-drawer/payment-drawer.tsx
- frontend/src/components/task/task-assignment.js
- frontend/src/components/task/task.js
This pull request introduces several new components and updates existing ones to improve the design library and refactor some functionalities. The main changes include the addition of `Drawer` and `Introduction` components, updates to `PriceInput`, and modifications to the `TaskAssignment` component to use the new `Drawer` and `Introduction` components.
* [`frontend/src/components/design-library/molecules/drawer/drawer.tsx`](diffhunk://#diff-c7c46ad52bdf245d06bff6cc1013d732ec6017e98d7cfe4758efc86a75806c8eR1-R70): Added a new `Drawer` component with close button functionality and styling.
* [`frontend/src/components/design-library/molecules/introduction/introduction.tsx`](diffhunk://#diff-225063ebac44f141709ef572411020c7adfac76e005e1e1706c7926a1511f029R1-R41): Added a new `Introduction` …
> moving the invite and offer to the default drawer component

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/areas/public/features/task/task.js
- frontend/src/components/design-library/molecules/breadcrumbs/breadcrumb/breadcrumb.jsx
- frontend/src/components/design-library/molecules/breadcrumbs/breadcrumb/breadcrumb.stories.tsx
- frontend/src/components/design-library/molecules/dialogs/issue-message-author-dialog/issue-message-author-dialog.stories.tsx
- frontend/src/components/design-library/molecules/dialogs/issue-message-author-dialog/issue-message-author-dialog.tsx
- frontend/src/components/design-library/molecules/dialogs/issue-reports-dialog/issue-reports-dialog.stories.tsx
- frontend/src/components/design-library/molecules/dialogs/issue-reports-dialog/issue-reports-dialog.tsx
- frontend/src/components/design-library/molecules/lists/issue-author-list/issue-author-list.stories.tsx
- frontend/src/components/design-library/molecules/lists/issue-author-list/issue-author-list.tsx
- frontend/src/components/design-library/molecules/lists/issue-labels-list/issue-labels-list.stories.tsx
- frontend/src/components/design-library/molecules/lists/issue-labels-list/issue-labels-list.tsx
- frontend/src/components/design-library/molecules/sections/issue-header/issue-header.stories.tsx
- frontend/src/components/design-library/molecules/sections/issue-header/issue-header.tsx
- frontend/src/components/design-library/organisms/layouts/issue-content/issue-content-placeholder.tsx
- frontend/src/components/design-library/organisms/layouts/issue-content/issue-content.stories.tsx
- frontend/src/components/design-library/organisms/layouts/issue-content/issue-content.tsx
This pull request includes several updates to the `frontend/package-lock.json` and `frontend/src/components` files. The changes focus on updating dependencies and refactoring the `Task` component to use the `IssueContent` component for better code organization and readability.
Dependency updates:
* Added `html-react-parser` version `5.2.3` to `frontend/package-lock.json` and `frontend/package.json` to parse HTML strings into React components. [[1]](diffhunk://#diff-4a2d9aa3e849b134993936ca81b83fb139edd2b0218077ab0f403b8c4803c62aR52) [[2]](diffhunk://#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R123)
* Updated `domutils` from version `3.0.1` to `3.2.2` in `frontend/package-lock.json` to include the latest bug fixes and improvements.
* Added `html-dom-parser` …
> Issue content component handling all cases

- frontend/src/components/areas/private/components/session/login-button.tsx
- frontend/src/components/areas/private/components/session/login-page.js
- frontend/src/components/design-library/atoms/inputs/checkboxes/checkboxes.stories.tsx
- frontend/src/components/design-library/atoms/inputs/checkboxes/checkboxes.tsx
- frontend/src/components/design-library/atoms/inputs/fields/user-role-field/user-role-field.stories.tsx
- frontend/src/components/design-library/atoms/inputs/fields/user-role-field/user-role-field.tsx
- frontend/src/components/design-library/molecules/form-section/login-form/login-form-reset/login-form-reset.tsx
- frontend/src/components/design-library/molecules/form-section/login-form/login-form-signup/login-form-signup.stories.tsx
- frontend/src/components/design-library/molecules/form-section/login-form/login-form-signup/login-form-signup.tsx
- frontend/src/containers/common.js
- frontend/src/containers/login-page.js
- frontend/src/hooks/use-common-actions.tsx
- frontend/src/main/routes.js
- modules/users/userBuilds.js
- test/user.test.js
This pull request introduces significant updates to the login and form components, refactors the `LoginPage` to use functional components and hooks, and enhances the `Checkboxes` component with a "Select All" feature. Additionally, a new `UserRoleField` component is introduced, and the `LoginFormReset` component is updated with improved validation logic. Below is a summary of the most important changes grouped by theme:
* Refactored `LoginPage` from a class-based component to a functional component using React hooks (`useState`, `useEffect`, `useParams`, `useHistory`). This includes replacing lifecycle methods with `useEffect` and simplifying state management. (`[[1]](diffhunk://#diff-33f266ddb654b20b18a1638a1d11b88f98a82e45878daf7afa03eb7e12bcbcedL1-R16)`, …
> Creating user role component to choose a role on signup

- README.md
> Closes #00
Provide a brief description of the changes made in this pull request.
Explain the purpose of this pull request and the problem it aims to solve.
Provide a detailed explanation of the solution implemented and any relevant information. Include any code changes or new features.
Include any relevant screenshots or images to showcase the changes made.
Link any related issues that this pull request addresses.
Include any additional notes or information that may be relevant to this pull request.
Please ensure that your pull request follows the guidelines outlined in the project's [CONTRIBUTING.md](https://github.com/<username>/<repository>/blob/master/CONTRIBUTING.md) file.
Thank you for your contribution!
> docs: edited the license link

- modules/app/controllers/webhooks/webhook-connect.js
- modules/app/controllers/webhooks/webhook-platform.js
- modules/webhooks/transferReversed.js
- scripts/webhook_script.js
- test/data/stripe/stripe.webhook.transfer.reversed.js
- test/webhook.connect.test.js
- test/webhook.platform.test.js
This pull request adds support for handling Stripe `transfer.reversed` webhook events in both the Connect and Platform webhook controllers. It introduces new logic to update transfer statuses and notify users when a transfer is reversed, and includes comprehensive test coverage for this new webhook event.
**Webhook event handling improvements:**
* Added a new handler `transferReversed` in `modules/webhooks/transferReversed.js` to process `transfer.reversed` events. This handler updates the status of relevant `PaymentRequestTransfer` and `Transfer` records, sends notification emails to users, and logs errors as needed.
* Registered the new `transferReversed` handler in both `webhook-connect.js` and `webhook-platform.js`, so that `transfer.reversed` events are correctly routed and …
> handling reversed transfers
